---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MyPC.
--- DateTime: 2022/5/16 16:55
---
name = 'ddd'
age = 18
man = true
level = nil

arr_table = {'', 0, true, nil}
print(#arr_table)


